"""implementei o rbac

Revision ID: 12e68d08f3ac
Revises: 750a0f374b46
Create Date: 2025-12-11 09:52:03.078880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e68d08f3ac'
down_revision = '750a0f374b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###