"""add image ao card

Revision ID: 1858ed39d1ec
Revises: fbc1ac278747
Create Date: 2025-12-09 19:24:11.619414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1858ed39d1ec'
down_revision = 'fbc1ac278747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_url', sa.String(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('cards', 'image_url')
    # ### end Alembic commands ###