"""correcao konami id jsonb

Revision ID: 20ea4f461b41
Revises: a77dd3526054
Create Date: 2025-12-09 18:07:01.540844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20ea4f461b41'
down_revision = 'a77dd3526054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('builds_consulted', sa.Integer(), nullable=True),
    sa.Column('gameplay_questions', sa.Integer(), nullable=True),
    sa.Column('favorite_position', sa.String(), nullable=True),
    sa.Column('most_searched_player', sa.String(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_id'), 'user_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.alter_column('ai_cache', 'prompt_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Hash SHA256 da pergunta do usuário para busca rápida',
               existing_nullable=False)
    op.alter_column('ai_cache', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de expiração do cache (para invalidar respostas antigas)',
               existing_nullable=True)
    op.drop_constraint(op.f('ai_cache_prompt_hash_key'), 'ai_cache', type_='unique')
    op.drop_index(op.f('idx_ai_cache_expires_at'), table_name='ai_cache')
    op.drop_index(op.f('idx_ai_cache_prompt_hash'), table_name='ai_cache')
    op.create_index(op.f('ix_ai_cache_id'), 'ai_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ai_cache_prompt_hash'), 'ai_cache', ['prompt_hash'], unique=True)
    op.drop_table_comment(
        'ai_cache',
        existing_comment='Cache de respostas da IA para economizar chamadas de API',
        schema=None
    )
    op.alter_column('builds', 'is_official_meta',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se é uma build oficial recomendada pela IA',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('builds', 'meta_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Conteúdo adicional: dicas, playstyle, instruções, etc',
               existing_nullable=True)
    op.drop_index(op.f('idx_builds_card_id'), table_name='builds')
    op.drop_index(op.f('idx_builds_is_official_meta'), table_name='builds')
    op.drop_index(op.f('idx_builds_meta_content'), table_name='builds', postgresql_using='gin')
    op.drop_index(op.f('idx_builds_user_id'), table_name='builds')
    op.create_index(op.f('ix_builds_id'), 'builds', ['id'], unique=False)
    op.drop_constraint(op.f('builds_user_id_fkey'), 'builds', type_='foreignkey')
    op.drop_constraint(op.f('builds_card_id_fkey'), 'builds', type_='foreignkey')
    op.create_foreign_key(None, 'builds', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'builds', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'builds',
        existing_comment='Configurações de pontos de habilidade para cada carta',
        schema=None
    )
    op.alter_column('cards', 'player_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Referência ao jogador real',
               existing_nullable=True)
    op.alter_column('cards', 'version',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Versão da carta (Featured, Legend, Icon, etc)',
               existing_nullable=True)
    op.alter_column('cards', 'stats_base',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Estatísticas base da carta em formato JSON',
               existing_nullable=True)
    op.drop_constraint(op.f('cards_konami_id_key'), 'cards', type_='unique')
    op.drop_index(op.f('idx_cards_konami_id'), table_name='cards')
    op.drop_index(op.f('idx_cards_name'), table_name='cards')
    op.drop_index(op.f('idx_cards_player_id'), table_name='cards')
    op.drop_index(op.f('idx_cards_position'), table_name='cards')
    op.drop_index(op.f('idx_cards_version'), table_name='cards')
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.drop_constraint(op.f('cards_player_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'players', ['player_id'], ['id'])
    op.drop_table_comment(
        'cards',
        existing_comment='Cartas/versões específicas dos jogadores (ex: Messi Icon, Messi Featured 2024)',
        schema=None
    )
    op.drop_column('cards', 'konami_id')
    op.alter_column('gameplay_tips', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Categoria da dica (defesa, ataque, drible, passe, etc)',
               existing_nullable=False)
    op.alter_column('gameplay_tips', 'pain_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição do problema que o jogador enfrenta',
               existing_nullable=True)
    op.alter_column('gameplay_tips', 'solution',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Solução detalhada do problema',
               existing_nullable=False)
    op.drop_index(op.f('idx_gameplay_tips_category'), table_name='gameplay_tips')
    op.drop_index(op.f('idx_gameplay_tips_created_by'), table_name='gameplay_tips')
    op.create_index(op.f('ix_gameplay_tips_category'), 'gameplay_tips', ['category'], unique=False)
    op.create_index(op.f('ix_gameplay_tips_id'), 'gameplay_tips', ['id'], unique=False)
    op.drop_constraint(op.f('gameplay_tips_created_by_user_id_fkey'), 'gameplay_tips', type_='foreignkey')
    op.create_foreign_key(None, 'gameplay_tips', 'users', ['created_by_user_id'], ['id'])
    op.drop_table_comment(
        'gameplay_tips',
        existing_comment='Dicas e soluções de gameplay (defesa, ataque, passes, etc)',
        schema=None
    )
    op.alter_column('players', 'real_position',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Posição principal do jogador na vida real',
               existing_nullable=True)
    op.drop_index(op.f('idx_players_konami_id'), table_name='players')
    op.drop_index(op.f('idx_players_name'), table_name='players')
    op.drop_index(op.f('idx_players_nationality'), table_name='players')
    op.drop_constraint(op.f('players_konami_player_id_key'), 'players', type_='unique')
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.drop_table_comment(
        'players',
        existing_comment='Jogadores reais do eFootball (ex: Messi, Neymar, CR7)',
        schema=None
    )
    op.drop_column('players', 'konami_player_id')
   
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_is_premium'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_table_comment(
        'users',
        existing_comment='Usuários do sistema (sincronizado com Supabase Auth via UUID)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Usuários do sistema (sincronizado com Supabase Auth via UUID)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_index(op.f('idx_users_is_premium'), 'users', ['is_premium'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'last_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data do último reset do contador diário',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'daily_questions_used',
               existing_type=sa.INTEGER(),
               comment='Contador de perguntas feitas hoje',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               comment='Se o usuário é premium (desabilita limite de perguntas)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'premium', 'free', name='userrole'),
               type_=postgresql.ENUM('admin', 'premium', 'free', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::user_role"))
    op.alter_column('users', 'platform',
               existing_type=sa.Enum('console', 'pc', 'mobile', name='userplatform'),
               type_=postgresql.ENUM('console', 'pc', 'mobile', name='user_platform'),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='UUID do usuário no Supabase Auth',
               existing_nullable=False)
    op.add_column('players', sa.Column('konami_player_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID oficial do jogador na base Konami'))
    op.create_table_comment(
        'players',
        'Jogadores reais do eFootball (ex: Messi, Neymar, CR7)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.create_unique_constraint(op.f('players_konami_player_id_key'), 'players', ['konami_player_id'])
    op.create_index(op.f('idx_players_nationality'), 'players', ['nationality'], unique=False)
    op.create_index(op.f('idx_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('idx_players_konami_id'), 'players', ['konami_player_id'], unique=False)
    op.alter_column('players', 'real_position',
               existing_type=sa.VARCHAR(length=50),
               comment='Posição principal do jogador na vida real',
               existing_nullable=True)
    op.create_table_comment(
        'gameplay_tips',
        'Dicas e soluções de gameplay (defesa, ataque, passes, etc)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'gameplay_tips', type_='foreignkey')
    op.create_foreign_key(op.f('gameplay_tips_created_by_user_id_fkey'), 'gameplay_tips', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_gameplay_tips_id'), table_name='gameplay_tips')
    op.drop_index(op.f('ix_gameplay_tips_category'), table_name='gameplay_tips')
    op.create_index(op.f('idx_gameplay_tips_created_by'), 'gameplay_tips', ['created_by_user_id'], unique=False)
    op.create_index(op.f('idx_gameplay_tips_category'), 'gameplay_tips', ['category'], unique=False)
    op.alter_column('gameplay_tips', 'solution',
               existing_type=sa.TEXT(),
               comment='Solução detalhada do problema',
               existing_nullable=False)
    op.alter_column('gameplay_tips', 'pain_description',
               existing_type=sa.TEXT(),
               comment='Descrição do problema que o jogador enfrenta',
               existing_nullable=True)
    op.alter_column('gameplay_tips', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Categoria da dica (defesa, ataque, drible, passe, etc)',
               existing_nullable=False)
    op.add_column('cards', sa.Column('konami_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'cards',
        'Cartas/versões específicas dos jogadores (ex: Messi Icon, Messi Featured 2024)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_player_id_fkey'), 'cards', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.create_index(op.f('idx_cards_version'), 'cards', ['version'], unique=False)
    op.create_index(op.f('idx_cards_position'), 'cards', ['position'], unique=False)
    op.create_index(op.f('idx_cards_player_id'), 'cards', ['player_id'], unique=False)
    op.create_index(op.f('idx_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('idx_cards_konami_id'), 'cards', ['konami_id'], unique=False)
    op.create_unique_constraint(op.f('cards_konami_id_key'), 'cards', ['konami_id'])
    op.alter_column('cards', 'stats_base',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estatísticas base da carta em formato JSON',
               existing_nullable=True)
    op.alter_column('cards', 'version',
               existing_type=sa.VARCHAR(length=100),
               comment='Versão da carta (Featured, Legend, Icon, etc)',
               existing_nullable=True)
    op.alter_column('cards', 'player_id',
               existing_type=sa.INTEGER(),
               comment='Referência ao jogador real',
               existing_nullable=True)
    op.create_table_comment(
        'builds',
        'Configurações de pontos de habilidade para cada carta',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'builds', type_='foreignkey')
    op.drop_constraint(None, 'builds', type_='foreignkey')
    op.create_foreign_key(op.f('builds_card_id_fkey'), 'builds', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('builds_user_id_fkey'), 'builds', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_builds_id'), table_name='builds')
    op.create_index(op.f('idx_builds_user_id'), 'builds', ['user_id'], unique=False)
    op.create_index(op.f('idx_builds_meta_content'), 'builds', ['meta_content'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_builds_is_official_meta'), 'builds', ['is_official_meta'], unique=False)
    op.create_index(op.f('idx_builds_card_id'), 'builds', ['card_id'], unique=False)
    op.alter_column('builds', 'meta_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Conteúdo adicional: dicas, playstyle, instruções, etc',
               existing_nullable=True)
    op.alter_column('builds', 'is_official_meta',
               existing_type=sa.BOOLEAN(),
               comment='Se é uma build oficial recomendada pela IA',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'ai_cache',
        'Cache de respostas da IA para economizar chamadas de API',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_ai_cache_prompt_hash'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_id'), table_name='ai_cache')
    op.create_index(op.f('idx_ai_cache_prompt_hash'), 'ai_cache', ['prompt_hash'], unique=False)
    op.create_index(op.f('idx_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False)
    op.create_unique_constraint(op.f('ai_cache_prompt_hash_key'), 'ai_cache', ['prompt_hash'])
    op.alter_column('ai_cache', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de expiração do cache (para invalidar respostas antigas)',
               existing_nullable=True)
    op.alter_column('ai_cache', 'prompt_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='Hash SHA256 da pergunta do usuário para busca rápida',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###