"""rm- statusbase do Card

Revision ID: 750a0f374b46
Revises: 1858ed39d1ec
Create Date: 2025-12-09 19:44:52.494680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '750a0f374b46'
down_revision = '1858ed39d1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'stats_base')
   


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('cards', sa.Column('stats_base', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###