"""correcao user(rm- nickname, realposition)

Revision ID: fbc1ac278747
Revises: 20ea4f461b41
Create Date: 2025-12-09 18:24:14.181077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbc1ac278747'
down_revision = '20ea4f461b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'real_position')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID do usuário no Supabase Auth',
               existing_nullable=False)
    
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se o usuário é premium (desabilita limite de perguntas)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'daily_questions_used',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Contador de perguntas feitas hoje',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'last_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data do último reset do contador diário',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_nickname_key'), 'users', type_='unique')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_nickname_key'), 'users', ['nickname'])
    op.alter_column('users', 'last_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data do último reset do contador diário',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'daily_questions_used',
               existing_type=sa.INTEGER(),
               comment='Contador de perguntas feitas hoje',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               comment='Se o usuário é premium (desabilita limite de perguntas)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'premium', 'free', name='userrole'),
               type_=postgresql.ENUM('admin', 'premium', 'free', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::user_role"))
    op.alter_column('users', 'platform',
               existing_type=sa.Enum('console', 'pc', 'mobile', name='userplatform'),
               type_=postgresql.ENUM('console', 'pc', 'mobile', name='user_platform'),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='UUID do usuário no Supabase Auth',
               existing_nullable=False)
    op.add_column('players', sa.Column('real_position', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###